[package]
name = "aws-service-references"
version = "0.1.0"
edition = "2024"

[build-dependencies]
color-eyre = "0.6.5"
rustfmt-wrapper = "0.2.1"
service-code-generator = { version = "0.1.0", path = "../service-code-generator" }
