[package]
name = "aws-service-reference-types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
thiserror = "2.0.12"

[dev-dependencies]
color-eyre = "0.6.5"
